[tool.poetry]
name = "celery-types"
version = "0.1.0"
description = ""
authors = ["Steve Dignam <steve@dignam.xyz>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
bpython = "^0.21.0"
celery = "^5.0"
black = {version = "20.8b1",allows-prereleases = true}
flake8 = "^3.8"
flake8-pyi = "^20.10"
isort = "^4.3"
django-types = "^0.3.1"
django = "^3.1"
mypy = "^0.800.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
